@echo off
echo Abrindo o terminal e instalando a biblioteca Selenium...
echo Isso pode levar alguns minutos...
start cmd /k "python -m pip install selenium & echo. & echo Instalacao concluida. Pressione ENTER para fechar."